name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - master
    paths:
      - "**.js"
  issues:
    types:
      - edited

jobs:
  check-bats-version:
    runs-on: windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install hello-world
      - run: "::echo file=index.js,line=1::missing semicolon"
